// <auto-generated />
namespace PassionProject_N01540458.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class foodcategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foodcategories));
        
        string IMigrationMetadata.Id
        {
            get { return "202302091445300_foodcategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
